version: '0.1'

services:
  database:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: 'freezer_db3000'
    restart: always
    environment:
      MARIADB_USER: freezer
      MARIADB_PASSWORD: freezer
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MYSQL_DATABASE: freezer_db
    expose:
      - 3306
    networks:
      net_worth:
        ipv4_address: 10.5.0.5
    volumes:
      - 'mariadb:/var/lib/mysql'

# pour backup : https://techoverflow.net/2020/12/01/how-to-backup-data-from-docker-compose-mariadb-container-using-mysqldump/i
  jenkinsagent:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: 'jean-kins'
    restart: always
    privileged: true
    user: root
    networks:
      net_worth:
        ipv4_address: 10.5.0.3
    expose:
      - 22
    volumes:
      - "mariadb:/home/jenkins/workspace/'Better Freezer'/mariadb"
      - "python:/home/jenkins/workspace/'Better Freezer'/docker_python"
      - "nginx:/home/jenkins/workspace/'Better Freezer'/dockernginx"
      - "musics:/home/jenkins/workspace/'Better Freezer'/proftpd"
  nginx:
    build:
      context: ./dockernginx
      dockerfile: Dockerfile
    container_name: 'nginxcontainer'
    restart: always
    expose :
          - 80
    networks:
      net_worth:
        ipv4_address: 10.5.0.2

  pythonserv:
    build:
      context: ./docker_python
      dockerfile: Dockerfile
    container_name: 'pythoncontainer'
    restart: always
    networks:
      net_worth:
        ipv4_address: 10.5.0.4
    volumes:
          - 'nginx:/srv/pythoncgi/'

  proftpd:
    image: bogem/ftp
    container_name: 'proftpdcontainer'
    environment:
      FTP_USER: bidon
      FTP_PASS: bidon
      PASV_ADRESS: 127.0.0.1
    restart: always
    networks:
      net_worth:
        ipv4_address: 10.5.0.6
    volumes:
      - 'musics:/etc/'

              # declaration des volumes
volumes:
    mariadb:
    python:
    nginx:
    musics:
      #declaration networks
networks:
    net_worth:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
            gateway: 10.5.0.1
