---
- name: Update web servers
  hosts: control
  remote_user: root

  tasks:
  - name: Ensure docker & git installed
    community.general.pacman:
      name: git
      name: docker
      state: installed
  - name: ensure docker is running
    ansible.builtin.systemd:
    name: docker
    state: restarted
  - name: manage docker
    community.docker.docker_container:

    

