---
- name: Update web servers
  hosts: hosts
  remote_user: root
  become: yes

  tasks:
  - name: Ensure docker & git installed
    community.general.pacman:
      name: git
      name: docker
      name: docker-compose
      name: python-pip
      state: installed

  - name: Clone a github repository
    git:
      repo: https://github.com/M-D-Q/freezer.git
      dest: /tmp/example
      clone: yes
      update: yes
  
  - name: pip instal
    pip:
      name: docker
      name: docker-compose

  - name: ensure docker is running
    ansible.builtin.systemd:
      name: docker
      state: restarted

##############################################

- name: deploy docker compose 1 on host 1
  hosts: maxime

  tasks:

  - name: deploy dockompose1
    community.docker.docker_compose:
      project_src: /etc/freezer/dockompose1.yml
      state: present


#################################################

- name: deploy docker compose 2 on host 2
  hosts: me

  tasks:

  - name: deploy dockompose2
    community.docker.docker_compose:
      project_src: /tmp/example
      files: dockompose2.yml
      state: present
