---
- name: Update web servers
  hosts: hosts
  become: yes

  tasks:
  - name: Ensure docker & git installed
    community.general.pacman:
      name: git
      name: docker
      name: docker-compose
      name: python-pip
      state: installed

        #- name: Clone a github repository
    #git:
      # repo: https://github.com/M-D-Q/freezer.git
      #repo: https://framagit.org/MDQ/test_nginx_jenkins.git
        #dest: /tmp/example
        #clone: yes
        # update: yes

  - name: clone
    ansible.builtin.shell:
      cmd: (cd /tmp/example && git clone https://github.com/M-D-Q/freezer.git) || (cd /tmp/example/freezer && git pull)

  - name: pip instal
    pip:
      name: docker
      name: docker-compose

  - name: ensure docker is running
    ansible.builtin.systemd:
      name: docker
      state: started

##############################################

- name: deploy docker compose 1 on host 1
  hosts: maxime
  become: yes
  tasks:

  - name: deploy dockompose1
    community.docker.docker_compose:
      project_src: /tmp/example/freezer
      files: dockompose1.yml
      state: present


#################################################

- name: deploy docker compose 2 on host 2
  hosts: me
  become: yes
  tasks:

  - name: deploy dockompose2
    community.docker.docker_compose:
      project_src: /tmp/example/freezer
      files: dockompose2.yml
      state: present
